<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function createComment(Comment $comment)
    {
        $this->_em->persist($comment);
        $this->_em->flush();
    }
}
