services:
    app.exception_listener:
        class: AppBundle\EventListener\NewCommentListener
        arguments: ["@tysdever_notifier.email_notifier", "%mailer_user%"]
        tags:
            - { name: kernel.event_listener, event: app.comment.new, method: onNewCommentAdded }